import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { usePathname } from "next/navigation";
import Slider from "@/components/Header/SliderHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const nunito = Nunito({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="bg-blue-50 md:flex w-screen">
      <header className={`md:w-1/5 ${nunito.className} `}>
        <Header />
        <Slider />
      </header>
      <section className={`w-full md:pt-0 pt-10 ${nunito.className}`}>
        {children}
      </section>
    </section>
  );
}
